# Generated by https://smithery.ai. See: https://smithery.ai/docs/build/project-config
FROM node:lts-alpine

# Install dependencies
WORKDIR /app
COPY package.json package-lock.json* tsconfig.json ./
RUN npm install --ignore-scripts

# Copy source and build
COPY src ./src
RUN npm run build

# Default command to start the MCP server
CMD ["node", "src/mcp/server.js"]
